name: Compile and Release CSS

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: false

      - name: Compile CSS from SASS files
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: src/userChrome.sass
          destination: userChrome.css

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: FirefoxCSS
          tag_name: v0.1.0
          prerelease: true
          generate_release_notes: true
          files: userChrome.css
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
